sudo: required

language: python
python:
  # 2.7 is rejected by dependency mypy-lang
  - 3.3
  - 3.4
  - 3.5
  - 3.6-dev
jdk:
  - oraclejdk8

dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - avsm  # OPAM stable
      - hvr-ghc  # Haskell
    packages:
      - cabal-install
      - chktex
      - clang-3.4
      - cppcheck
      - flawfinder
      - gfortran
      - ghc
      - haskell-platform
      - indent
      - libblas-dev
      - liblapack-dev
      - libperl-critic-perl
      - libxml2-utils
      - luarocks
      - menhir
      - mono-mcs
      - ocaml
      - opam
      - oracle-java9-set-default
      - php-codesniffer
      - verilator

cache:
  pip: true
  directories:
    # Installed language package caches
    - ~/.cabal
    - ~/R/Library
    - ~/.julia
    - $TRAVIS_BUILD_DIR/node_modules
    - $TRAVIS_BUILD_DIR/.bundle
    - $TRAVIS_BUILD_DIR/vendor
    # coala managed data
    - ~/nltk_data
    - ~/.local/share/coala-bears
    # .deb cache
    - ~/.apt-cache
    # Installed linters
    - ~/infer-linux64-v0.7.0
    - ~/pmd-bin-5.4.1
    - ~/bakalint-0.4.0
    - ~/dart-sdk/bin
    - ~/.local/tailor/

env:
  global:
    - CIRCLE_NODE_INDEX=-1  # Avoid accidentially being a CircleCI worker
    - USE_PPAS="marutter/rdev staticfloat/juliareleases ondrej/golang"
    - R_LIB_USER=~/R/Library
    - LINTR_COMMENT_BOT=false
    - PATH="$PATH:$TRAVIS_BUILD_DIR/node_modules/.bin:$TRAVIS_BUILD_DIR/vendor/bin:$HOME/dart-sdk/bin:$HOME/.cabal/bin:$HOME/infer-linux64-v0.7.0/infer/bin:$HOME/pmd-bin-5.4.1/bin:$HOME/bakalint-0.4.0:$HOME/.local/tailor/tailor-latest/bin"

before_install:
  - export TRAVIS_PYTHON_VERSION_MAJOR=${TRAVIS_PYTHON_VERSION%.[0-9]}
  - export TRAVIS_PYTHON_VERSION_MINOR=${TRAVIS_PYTHON_VERSION#[0-9].}
  - >
    if [[ $TRAVIS_PYTHON_VERSION_MINOR < 4 || $TRAVIS_PYTHON_VERSION_MAJOR == 2 ]]; then
      UNSUPPORTED=true
    fi

  - nvm install 4
  - nvm use 4
  # Remove Ruby directive from Gemfile as this image has 2.2.5
  - sed -i '/^ruby/d' Gemfile
  - mkdir -p ~/.apt-cache
  - if [[ "$UNSUPPORTED" != true ]]; then bash .ci/deps.sh; fi
  - if [[ "$UNSUPPORTED" != true ]]; then bash .ci/deps.shellcheck.sh; fi
  # https://github.com/coala/coala/issues/3183
  - cp requirements.txt requirements.orig
  - cat test-requirements.txt docs-requirements.txt bear-requirements.txt >> requirements.txt
  - sed -i '/^-r/d' requirements.txt
  # On unsupported versions, coala will be installed in the `script` block
  - >
    if [[ "$UNSUPPORTED" == true ]]; then
      sed -e '/^coala/d' requirements.txt > requirements.new
      mv requirements.new requirements.txt
    fi

before_script:
  - mv requirements.orig requirements.txt
  # nltk 3.2.2 dropped support for Python 3.3
  - >
    if [[ "$TRAVIS_PYTHON_VERSION" != "3.3" ]]; then
      python -m nltk.downloader punkt maxent_treebank_pos_tagger averaged_perceptron_tagger
    fi

script:
  - >
    if [[ "$UNSUPPORTED" == true ]]; then
      set -e
      python setup.py install | tee setup.err
      grep -q 'coala supports only python 3.4 or later' setup.err
      if grep -q 'Traceback (most recent call last)' setup.err; then
        false
      fi
    fi
  - if [[ "$UNSUPPORTED" == true ]]; then exit; fi
  - python setup.py bdist_wheel
  - pip install $(ls ./dist/*.whl)"[alldeps]"
  - bash .ci/tests.sh
  # Ensure bear requirements are in sync with the bear PipRequirement
  - .ci/generate_bear_requirements.py
  - git diff --exit-code bear-requirements.txt
  # https://github.com/coala/coala-bears/issues/1037
  - >
    if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
      sed -e '/bears = GitCommitBear/d' .coafile > .coafile.new
      mv .coafile.new .coafile
    fi
  - coala --non-interactive
  - bash .ci/deploy.coverage.sh
  - rm -rf docs/API && make -C docs clean
  - python setup.py docs

notifications:
  email: false
